FROM node
WORKDIR /usr/src/app
COPY ./package*.json ./
COPY ./tsconfig.json ./tsconfig.json
COPY ./src/ ./src/
RUN npm install -g typescript && npm install && npm run build
EXPOSE 3000
CMD [ "node", "./dist/server.js" ]
